### ISSUE TITLE
Area code is already set

### ISSUE THREAD

**Issue by RimpalBhensdadia** [magemojo/m2-ce-cron#57]
magento 2.2.3 version.

When we click on execute, it will giving this error: Area code is already set

![image](https://user-images.githubusercontent.com/44260848/47149672-e2debe80-d2f1-11e8-846d-61e922721077.png)

**Comment by inkobject** [comment]
Getting this error on Magento 2.2.6
This is specific to executing Job Code: magemojo_cron_cleanup command
I have not tried to execute the other Job Codes.

Error Dump:

```
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Area code is already set

Exception #0 (Magento\Framework\Exception\LocalizedException): Area code is already set
#0 /home/BLAH_BLAH/test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\State->setAreaCode('crontab')
#1 /home/BLAH_BLAH/test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\State\Interceptor->___callParent('setAreaCode', Array)
#2 /home/BLAH_BLAH/test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\State\Interceptor->Magento\Framework\Interception\{closure}('crontab')
#3 /home/BLAH_BLAH/test/generated/code/Magento/Framework/App/State/Interceptor.php(52): Magento\Framework\App\State\Interceptor->___callPlugins('setAreaCode', Array, Array)
#4 /home/BLAH_BLAH/test/app/code/MageMojo/Cron/Model/Schedule.php(473): Magento\Framework\App\State\Interceptor->setAreaCode('crontab')
#5 /home/BLAH_BLAH/test/app/code/MageMojo/Cron/Controller/Adminhtml/Reports/Execute.php(32): MageMojo\Cron\Model\Schedule->executeImmediate('magemojo_cron_c...')
#6 /home/BLAH_BLAH/test/generated/code/MageMojo/Cron/Controller/Adminhtml/Reports/Execute/Interceptor.php(24): MageMojo\Cron\Controller\Adminhtml\Reports\Execute->execute()
#7 /home/BLAH_BLAH/test/vendor/magento/framework/App/Action/Action.php(107): MageMojo\Cron\Controller\Adminhtml\Reports\Execute\Interceptor->execute()
#8 /home/BLAH_BLAH/test/vendor/magento/module-backend/App/AbstractAction.php(235): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /home/BLAH_BLAH/test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#10 /home/BLAH_BLAH/test/vendor/magento/framework/Interception/Interceptor.php(138): MageMojo\Cron\Controller\Adminhtml\Reports\Execute\Interceptor->___callParent('dispatch', Array)
#11 /home/BLAH_BLAH/test/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): MageMojo\Cron\Controller\Adminhtml\Reports\Execute\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#12 /home/BLAH_BLAH/test/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(MageMojo\Cron\Controller\Adminhtml\Reports\Execute\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /home/BLAH_BLAH/test/vendor/magento/framework/Interception/Interceptor.php(153): MageMojo\Cron\Controller\Adminhtml\Reports\Execute\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#14 /home/BLAH_BLAH/test/generated/code/MageMojo/Cron/Controller/Adminhtml/Reports/Execute/Interceptor.php(39): MageMojo\Cron\Controller\Adminhtml\Reports\Execute\Interceptor->___callPlugins('dispatch', Array, NULL)
#15 /home/BLAH_BLAH/test/vendor/magento/framework/App/FrontController.php(55): MageMojo\Cron\Controller\Adminhtml\Reports\Execute\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#16 /home/BLAH_BLAH/test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /home/BLAH_BLAH/test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#18 /home/BLAH_BLAH/test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#19 /home/BLAH_BLAH/test/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#20 /home/BLAH_BLAH/test/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /home/BLAH_BLAH/test/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#22 /home/BLAH_BLAH/test/vendor/magento/framework/App/Bootstrap.php(257): Magento\Framework\App\Http\Interceptor->launch()
#23 /home/BLAH_BLAH/test/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#24 {main}
```

**Comment by jeffwhitfield** [comment]
Same here. Also looks like jobs aren't being run at all.
